---
- hosts: all
  become: yes
  tasks:
     - name: nexus url
       get_url: 
          url: http://3.109.58.82:8081/nexus/service/local/repositories/mahesh/content/vprofile/vprofile-v1/1/vprofile-v1-1.war
          dest: /home/ec2-user
     - name: copy        
       copy:
          src: /home/ec2-user/vprofile-v1-1
          dest: /home/ec2-user/apache-tomcat-9.0.80/webapps
     - name: start service     
       shell: ./startup.sh
       args: 
          chdir: /home/ec2-user/apache-tomcat-9.0.80/bin/
