---
- hosts: all
  become: yes
  tasks:
     - name: nexus url
       get_url: 
          url: get_url: url=http://172.31.12.114:8081/nexus/content/repositories/mahesh/{{groupid}}/{{time}}/{{build}}/{{vprofile_version}}
          dest: /home/ec2-user
     - name: copy        
       copy:
          src: /home/ec2-user/{{vprofile_version}}
          dest: /home/ec2-user/apache-tomcat-9.0.80/webapps
     - name: start service     
       shell: ./startup.sh
       args: 
          chdir: /home/ec2-user/apache-tomcat-9.0.80/bin/
