---
- hosts: all
  become: yes
  tasks:
     - name: nexus url
       get_url:
         # url: http://3.109.58.82:8081/nexus/service/local/repositories/mahesh/content/vprofile/vprofile-v1/22/vprofile-v1-22.war
          url: http://3.7.46.160:8081/nexus/service/local/repositories/mahesh-vprofile/content/vrprofile-v1/vprofile/$BUILD_ID/vprofile-$BUILD_ID.war
          dest: /home/ec2-user
     - name: copy
       copy:
          src: /home/ec2-user/vprofile-v1-$BUILD_ID.war
          dest: /home/ec2-user/apache-tomcat-9.0.84/webapps
          remote_src: true
     - name: start service
       shell: nohup /home/ec2-user/apache-tomcat-9.0.84/bin/startup.sh

