apiVersion: apps/v1
kind: Deployment
metadata:
  name: mahesh-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: mahesh-cont
        image: mahesh986695/abcd
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
