---
- hosts: all
  become: yes
  tasks:
    - name: docker image
      shell: docker build -t mahesh986695/tom .
    - name: push image
      shell: docker push mahesh986695/tom:latest
    - name: run
      shell: docker run -d -p 8090:8080 mahesh986695/tom
